on:
    push:
        tags:
            - 'v*'

jobs:
    pypi-publish:
      name: Upload release to PyPI
    #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      runs-on: ubuntu-latest
      environment:
        name: pypi
        url: https://pypi.org/p/nodepad
      permissions:
        id-token: write
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install uv
          uses: astral-sh/setup-uv@v4
          with:
            version: "latest"
        - name: build
          run: uv build

        - name: Publish to PyPI  
          uses: pypa/gh-action-pypi-publish@release/v1