name: docs-build-deploy

on:
  push:
    branches: ["main"]

jobs:
  build-docs:
    runs-on: macos-14
    permissions: write-all
    env:
      version: 4.3
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: actions/setup-python@v5
        with:
            python-version: "3.11.7"
            cache: pip
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
              
      - name: Generate Node Docs
        run: |
          uv sync --all-extras --dev
          uv pip install -e .
          uv run docs/generate.py

      - name: Build Docs
        run: |
            cd docs
            uv run -m quartodoc build
            uv run quarto render


      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
            target: gh-pages
            path: docs
            render: false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
