name: Run Tests

on: 
    push:
      branches: ["main"]
    pull_request:
      branches: ["*"]
    
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 4
            fail-fast: false
            matrix:
              version: ["4.2", "4.3"]
              os: [macos-14]
        steps:
            - uses: actions/checkout@v4
            - name: Install Blender
              uses: BradyAJohnston/setup-blender@v1
              with:
                version: ${{ matrix.version }}
            - name: Run tests in Blender
              run: |
                blender -b -P tests/python.py --  -m uv run /Applications/Blender.app/Contents/Resources/${{ matrix.version }}/python/bin/pytest --cov --cov-report=xml
    
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
            
            - name: Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@v1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
    
